"""relacao usuarios todos

Revision ID: 9b2ce7cb3727
Revises: 69d3961e23a9
Create Date: 2024-07-25 23:34:16.427140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2ce7cb3727'
down_revision: Union[str, None] = '69d3961e23a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
